spring:
  application:
    name: cohort8th
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//221.148.97.239:1521/XEPDB1
    username: {SPRING_DATASOURCE_USERNAME}
    password: 1128
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 300MB

server:
  port: 80
#  address:

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*Mapper.xml
  type-aliases-package: com.newlecture.web.cohort8th.entity
logging:
  level:
    com.newlecture.web.cohort8th.repository: trace