spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: {SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    generate-ddl: true
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true